### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by Ellipse0934** [trickarcher/scanCUDA#1] opened 2020-04-25 01:45 UTC
Hi,
I was having a look at this and noticed that the GPU benchmarks seemed a bit off. On running [nvvp](https://developer.nvidia.com/nvidia-visual-profiler) for length = 10<sup>8</sup> I got :
![image](https://user-images.githubusercontent.com/7466364/80268236-22465200-86c3-11ea-87dc-d1d6fe9739a9.png)
Which is 360 ms on a GTX 1060(6GB). Even accounting for 2x SM's of the 1080 and the slightly higher clock/bandwidth 8.9ms seems impossibly hard. Maybe you accidentally reported the time of a kernel instance rather than the total compute time because I am getting 10ms minimum and 12ms avg for the `compact_offsets` kernel.

**Comment by trickarcher** [comment] 2020-04-25 05:26
Thanks for looking into this. 
Yes, the benchmarks seem quite off according to the `nvvp` and I should have mentioned this in the `ReadMe.md` but the benchmarks are the time spent in the GPU. You can use `nvprof` to get a much better overview of what's happening internally(stage-wise).
By "time spent in the GPU", I mean after the initial `Host->Device` Transfer and before the final `Device->Host` Transfer. The benchmarks include the following computations `reducing to a scan problem - kernel` -> `Device-to-Device Transfer` ->  `scan kernel` which is based on Hillis-Steele scan algorithm.
I had discussed this exact same issue with Jim, and we both agreed on the fact that we shouldn't include data transfer into benchmarks simply because of the fact an Awkward user would transfer the data to the GPU, do a lot of operations on it(as opposed to only one) and then copy it back. The main intention would be to operate within the GPU memory and once done, it can be transferred back to the host for further analysis or conversions to different types like Arrow or Parquet.
I do have some older benchmark that timed the entire operation. It was around 600 ms for 10^9 array int64_t length compared to 229 ms which the i7 processor took.
Please let me know if there's any other issue. Thanks!

**Comment by Ellipse0934** [comment] 2020-04-25 07:25
360ms excludes the HtoD and DtoH transfers. You are benchmarking each kernel call but since you have multiple kernels the total time is going to be significantly higher than 8.9ms for 10<sup>8</sup> elements.

> You can use nvprof to get a much better overview of what's happening internally(stage-wise).

I have a guess that you accidentally noted the minimum time instead of the total time for your kernels. 
![image](https://user-images.githubusercontent.com/7466364/80273422-7ff09380-86ef-11ea-88aa-f4c377f03f46.png)

Note that in the image(original post) there is a `Session` time which is 1.13 seconds which is the entire time GPU is used and the `compute` time which is 360ms which starts at the first `compute_offsets` kernel call and finishes at the last `compact_offsets` kernel call. The latter excludes the `cudaFree `and DtoD transfer though and only includes kernel execution time.

Timeline breakdown is (GTX1060):

1. `compute_offsets` : 10.42ms         
2. `cudaFree` x2:        16.45ms        (10.78 + 5.67 )  (to free `d_fromstarts` and `d_fromstarts`)
3. `cudaMalloc`:           4.85ms         (5.67 + 4.85)     (`d_in` and `d_out`)
4. `MemcpyDtoD`:      12.01ms
5. `compact_offsets`:340.63ms         27 kernel instances with avg time 12.61ms

Bringing the total time to around 384ms. Repeating myself, a GTX 1080 has double the SM's and a touch better circuitry and clock rate. That cannot possibly result in a such a drastic difference.


EDIT: Different test runs were used for the image and for the breakdown table as I wanted to write the correct `cudaFree` timings.

**Comment by trickarcher** [comment] 2020-04-25 08:09
The `compact_offsets` kernel is definitely off. Can you check your device throughput, please? And are you by any chance on a laptop? I ran the example.cpp for 10^8 elements and these are the results I got.
![screenshot_20200425_131403](https://user-images.githubusercontent.com/39878675/80274409-b7633e00-86f7-11ea-9647-674d40a15018.png) The times are less than half of yours though. 
I might have messed up the benchmarks a bit, I realize that now since, I can't run my library for 10^9 elements(I didn't add the `breaking the array into chunks` feature yet).  So in all likelihood, the 10^7 elements case took 8.9 ms and the 10^8 case took 108 ms the last time I checked. I might have messed up the zeros in the `ReadMe.md` :P. Thanks for pointing it out! I have confirmed this again below, which is very near to the reported results. (For 10^7). 
![rsz_screenshot_20200425_133535](https://user-images.githubusercontent.com/39878675/80274675-d82c9300-86f9-11ea-80c7-0684dc8c4965.png)

**Comment by trickarcher** [comment] 2020-04-25 08:16
Also, I think that I need to mention this. I was using the Cuda API Timer internally(`CudaEventRecord`), and the benchmarks reported are from those. I didn't use `nvprof` for the benchmarks although now I see that would have been a much better option to avoid confusion.

**Comment by Ellipse0934** [comment] 2020-04-25 08:21
I am on a desktop. Half the amount of time seems correct due to different models.(1080 vs 1060)
> 10^8 case took 108 ms the last time I checked.

Doubt it, here itself you have acquired over 150ms from the kernels + DtoD transfers.

> Also, I think that I need to mention this. I was using the Cuda API Timer internally(CudaEventRecord), and the benchmarks reported are from those.

You perhaps placed the record calls at the wrong point because there is never a significant difference (like here). I have used both and read some literature on their comparison.

**Comment by trickarcher** [comment] 2020-04-25 08:32
> You perhaps placed the record calls at the wrong point because there is never a significant difference (like here).

Unfortunately, I'll have to dig through stuff before I can come across that script. I doubt I made that mistake though.

I'll update the benchmarks from nvprof and maybe attach a few screenshots to validate the same. Does that seem okay to you?

**Comment by trickarcher** [comment] 2020-04-25 08:38
> Doubt it, here itself you have acquired over 150ms from the kernels + DtoD transfers.

In my personal experience you can easily gain performance if there's no other process running on the GPU simply due to the availability of more GPU memory. The server I used just now has only one GTX 1080 equipped and the Xorg processes are running which definitely reduces performance. I had used a PC with a  Multi GPU setup with one of the GPU's sitting idle for the earlier benchmarks so that might be the cause of the speedup.

**Comment by trickarcher** [comment] 2020-04-25 09:57
I have updated the ReadME.md with the corrected benchmarks and images. Please close this issue if you think I have addressed all your concerns.

**Closed as completed** 2020-05-04 17:51 UTC
